Repository souleimaneelqodsi/recipes, pull requests merged in 2025-05, with the labels that each got.

#11 UserSchema implementation
  api/models/user_shema.php
Labels: enhancement

#10 Feature/back/user controller
  api/controllers/auth_controller.php
  api/controllers/comment_controller.php
  api/controllers/recipe_controller.php
  api/controllers/user_controller.php
  api/index.php
  api/models/auth_schema.php
  api/models/recipe_schema.php
  api/models/user_schema.php
  api/models/user_shema.php
  api/router.php
  api/utils/errors.php
  api/utils/session.php
  api/utils/validator.php
Labels: documentation, enhancement, bug-fix

#18 la page connexion
  api/data/users.json
  connexion.html
  js/script.js
Labels: enhancement

#17 appel a la route published
  api/controllers/recipe_controller.php
  api/data/recipes.json
  js/script.js
Labels: bug, enhancement, bug-fix

#22 Feature/front/profil
  api/controllers/comment_controller.php
  api/controllers/photo_controller.php
  api/controllers/recipe_controller.php
  api/cookie.txt
  api/data/recipes.json
  api/data/users.json
  api/models/comment_schema.php
  api/models/photo_schema.php
  api/models/recipe_schema.php
  api/router.php
  connexion.html
  js/script.js
  profil.html
  style/css/style.css
Labels: enhancement, bug-fix

#23 Feature/back/comments
  api/controllers/comment_controller.php
  api/cookie.txt
  api/data/users.json
  api/models/user_schema.php
  api/utils/validator.php
Labels: enhancement, bug-fix

#24 Feature/back/photos
  api/data/recipes.json
  api/data/users.json
  api/models/user_schema.php
  api/utils/validator.php
  cookie.txt
Labels: enhancement, bug-fix

#25 Few fixes relative to the constraints of the project
  api/controllers/recipe_controller.php
  api/controllers/user_controller.php
  api/data/users.json
  api/models/user_schema.php
  api/utils/session.php
  api/utils/validator.php
Labels: enhancement, bug-fix

#27 Final push
  .DS_Store
  api/controllers/auth_controller.php
  api/controllers/photo_controller.php
  api/cookie.txt
  api/data/recipes.json
  api/data/users.json
  api/models/user_schema.php
  api/router.php
  api/utils/validator.php
  connexion.html
  cookie.txt
  inscription.html
  js/script.js
  test_api.sh
Labels: enhancement, bug-fix

#28 Develop
  .DS_Store
  api/controllers/auth_controller.php
  api/controllers/photo_controller.php
  api/cookie.txt
  api/data/recipes.json
  api/data/users.json
  api/models/user_schema.php
  api/router.php
  api/utils/validator.php
  connexion.html
  cookie.txt
  inscription.html
  js/script.js
  test_api.sh
Labels: enhancement, bug-fix
